export const ARRIVAL_SET = 'ARRIVAL_SET';
export const DEPARTURE_SET = 'DEPARTURE_SET';
export const DAY_TYPE_SET = 'DAY_TYPE_SET';
export const ARRIVED_PRESSED = 'ARRIVED_PRESSED';
export const LEFT_PRESSED = 'LEFT_PRESSED';
export const TIME_CLEARED = 'TIME_CLEARED';
export const COMMENT_CHANGED = 'COMMENT_CHANGED';